config/routes.rb
Rails.application.routes.draw do

  resources :items, controller: "cart_items"

  resources :orders do
    member do
      get :pay_with_credit_card
     post :pay2go_cc_notify
     post :pay2go_atm_complete
    end
  end

  root "products#index"

  resources :carts do
     collection do
       post :checkout
       delete :clean
     end
   end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :account do
    resources :orders
  end

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
      member do
        post :add_to_cart
      end
    end

end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright 유2016 EC-Shop
    <br>Design by <a href="http://bohung-blog.logdown.com" target=_new>Bohung-Hung Liou</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
  <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand">
        <i class="fa fa-anchor" aria-hidden="true"> EC-Shop</i>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to("Product List", products_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to carts_path do  %>
            購物車 <i class="fa fa-shopping-cart"> </i> ( <%= render_cart_items_count(current_cart) %> )
          <% end %>
        </li>

        <% if !current_user %>
          <li> <button type="button" class="btn btn-default navbar-btn"> <%= link_to("註冊", new_user_registration_path) %></button> </li>
          <li> <button type="button" class="btn btn-default navbar-btn"> <%= link_to("登入", new_user_session_path) %></button> </li>
          <li> <button type="button" class="btn btn-default navbar-btn"> <%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %> </button></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
               <li>
                 <%= link_to("Admin 選單", admin_products_path ) %>
               </li>
              <% end %>
              <li>
                <%= link_to("個人訂單列表", account_orders_path ) %>
              </li>
               <li>
                 <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
               </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>